
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Card
{
public sealed partial class CardElement : Luban.BeanBase
{
    public CardElement(JSONNode _buf) 
    {
        { if(!_buf["CardType"].IsNumber) { throw new SerializationException(); }  CardType = (Card.CardType)_buf["CardType"].AsInt; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["AssetPath"].IsString) { throw new SerializationException(); }  AssetPath = _buf["AssetPath"]; }
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
    }

    public static CardElement DeserializeCardElement(JSONNode _buf)
    {
        return new Card.CardElement(_buf);
    }

    /// <summary>
    /// 卡牌类型
    /// </summary>
    public readonly Card.CardType CardType;
    /// <summary>
    /// 卡牌等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string AssetPath;
    /// <summary>
    /// id
    /// </summary>
    public readonly string Id;
   
    public const int __ID__ = 1499967470;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CardType:" + CardType + ","
        + "level:" + Level + ","
        + "AssetPath:" + AssetPath + ","
        + "id:" + Id + ","
        + "}";
    }
}
}

