
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Card
{ 
    public enum CardType
    {
        /// <summary>
        /// 正常手牌，没有特殊功能
        /// </summary>
        NORMAL = 1,
        /// <summary>
        /// 会产生特殊功能
        /// </summary>
        SPECIAL = 2,
    }

} 

