
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GridTileElement : Luban.BeanBase
{
    public GridTileElement(JSONNode _buf) 
    {
        { if(!_buf["tileType"].IsNumber) { throw new SerializationException(); }  TileType = (GridTileType)_buf["tileType"].AsInt; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["des"].IsString) { throw new SerializationException(); }  Des = _buf["des"]; }
    }

    public static GridTileElement DeserializeGridTileElement(JSONNode _buf)
    {
        return new GridTileElement(_buf);
    }

    /// <summary>
    /// 类型
    /// </summary>
    public readonly GridTileType TileType;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Des;
   
    public const int __ID__ = -340012760;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "tileType:" + TileType + ","
        + "icon:" + Icon + ","
        + "des:" + Des + ","
        + "}";
    }
}
}

