
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GridTileElements : Luban.BeanBase
{
    public GridTileElements(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["GridTileElement"].IsNumber) { throw new SerializationException(); }  GridTileElement = (GridTileType)_buf["GridTileElement"].AsInt; }
    }

    public static GridTileElements DeserializeGridTileElements(JSONNode _buf)
    {
        return new GridTileElements(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 元素类型
    /// </summary>
    public readonly GridTileType GridTileElement;
   
    public const int __ID__ = -1950460853;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "level:" + Level + ","
        + "GridTileElement:" + GridTileElement + ","
        + "}";
    }
}
}

