
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCardElements
{
    private readonly System.Collections.Generic.List<Card.CardElement> _dataList;

    private System.Collections.Generic.Dictionary<(string, int), Card.CardElement> _dataMapUnion;

    public TbCardElements(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<Card.CardElement>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Card.CardElement _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Card.CardElement.DeserializeCardElement(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int), Card.CardElement>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Id, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<Card.CardElement> DataList => _dataList;

    public Card.CardElement Get(string id, int level) => _dataMapUnion.TryGetValue((id, level), out Card.CardElement __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

