
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbGridTile
{
    private readonly System.Collections.Generic.List<GridTileElements> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), GridTileElements> _dataMapUnion;

    public TbGridTile(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<GridTileElements>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GridTileElements _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.GridTileElements.DeserializeGridTileElements(_ele);  }
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), GridTileElements>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Id, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<GridTileElements> DataList => _dataList;

    public GridTileElements Get(int id, int level) => _dataMapUnion.TryGetValue((id, level), out GridTileElements __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

